# A place to put variables that apply to all groups
# Here you can override defaults of ansible roles
# NOTE: these are defaults should not be touched by user
#      Please use -e,--extra-vars, @config-file.yml
#      to change variables
node_name: "kolla-node-aio"
ssh_connection_timeout: 300
image_pool: "/var/lib/libvirt/images"
image_path: "{{ image_pool }}/kolla-image.qcow2"
is_remote: false
remote_username: ubuntu
ram_size: 10000
cpu_count: 12
disk_size: 50
network_ssh: "nat1"
network_openstack: "nat2"
network_neutron: "nat3"
is_aio: true
mac_addresses: {}
vms_to_delete:
  - "{{ node_name }}"
kolla_user: "kolla"
kolla_ssh_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_kola"
ssh_config: "ssh_config"
kolla_python_interpereter: "/home/kolla/kolla/bin/python"
ansible_args: >-
  ansible_ssh_user={{ kolla_user }}
  ansible_become=True
  ansible_private_key_file={{ kolla_ssh_key }}
  ansible_python_interpreter={{ kolla_python_interpereter }}

node_vg: ubuntu-vg
node_lv: ubuntu-lv
globals_file: globals.yml
kolla_source_local_path: "../kolla-ansible"
kolla_source_node_path: "/home/kolla/kolla-ansible"
additional_upload_node_path: "/home/kolla"
additional_upload_mode: "0777"
git_patch_kolla: false
git_branch: master
git_patches: []
additional_uploads: []
additional_uploads_deploy_node: []
